<?php

use DOMDocument;
use DOMXPath;

class closeAllHtmlTags
{
    // Creates new DOM object with a given content
    // and then returns valid HTML generated by DOM.
    public function index($content)
    {
        $dom = new DOMDocument();
        // Prevents errors and warnings
        libxml_use_internal_errors(true);
        $dom->loadHTML('<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>'.$content);
        $xpath = new DOMXPath($dom);
        $content = '';
        $nodes = $dom->getElementsByTagName('body')[0]->childNodes;
        foreach($nodes as $node)
        {
            $content .= $dom->saveHTML($node);
        }
        return $content;
    }
}

